# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "partyhat"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["clooth"]
  s.date = "2011-12-15"
  s.description = "Versatile runescape gem offering useful tools for runescape-related apps"
  s.email = "zenverse@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/partyhat.rb",
    "lib/partyhat/activity.rb",
    "lib/partyhat/activity_comparison.rb",
    "lib/partyhat/calculators.rb",
    "lib/partyhat/calculators/combat.rb",
    "lib/partyhat/forums.rb",
    "lib/partyhat/forums/forum_post.rb",
    "lib/partyhat/forums/forum_thread.rb",
    "lib/partyhat/highscores.rb",
    "lib/partyhat/player.rb",
    "lib/partyhat/skill.rb",
    "lib/partyhat/skill_comparison.rb",
    "lib/partyhat/stat.rb",
    "lib/partyhat/util.rb",
    "partyhat.gemspec",
    "spec/activity_spec.rb",
    "spec/calculators_spec.rb",
    "spec/forums_spec.rb",
    "spec/highscores_spec.rb",
    "spec/player_spec.rb",
    "spec/skill_spec.rb",
    "spec/spec_helper.rb",
    "spec/stat_spec.rb",
    "spec/util_spec.rb"
  ]
  s.homepage = "http://github.com/clooth/partyhat"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "General Runescape Gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<curb>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-gem-adapter>, [">= 0"])
    else
      s.add_dependency(%q<curb>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-gem-adapter>, [">= 0"])
    end
  else
    s.add_dependency(%q<curb>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-gem-adapter>, [">= 0"])
  end
end

